#!/usr/bin/env python3
"""
Self-updating GitHub profile engine.

This is what makes the profile "next level": instead of relying only on
third-party badge services, the README is partly generated by this script,
which runs automatically every few hours via GitHub Actions.

It fills in the sections marked with:

    <!--START_SECTION:name-->
    ... auto-generated content ...
    <!--END_SECTION:name-->

Currently it updates:
  * live BTC/EUR price  (ties into my project_BTC_API)
  * a "days since my first commit" counter
  * a rotating tip of the day

No third-party libraries required — standard library only, so it runs
anywhere with zero install.
"""

import datetime
import json
import pathlib
import re
import urllib.request

README = pathlib.Path("README.md")

# Date of my first day on GitHub — used for the "days coding" counter.
FIRST_COMMIT = datetime.date(2022, 4, 10)

TIPS = [
    "Write code for the human who reads it next — that human is usually you.",
    "A function that does one thing is easier to test, name, and trust.",
    "`try/except` is not error handling — catching the *right* error is.",
    "Name things so clearly that comments become optional.",
    "Small commits tell a story; giant commits hide bugs.",
    "If it's not in version control, it doesn't exist.",
    "Read the standard library before reaching for a dependency.",
    "Make it work, make it right, make it fast — in that order.",
    "f-strings beat string concatenation every single time.",
    "The best debugger is a well-placed, well-named variable.",
    "Automate the boring stuff once, save the time forever.",
    "A failing test is a feature request from your future self.",
]


def replace_section(content: str, name: str, new_body: str) -> str:
    """Replace whatever is between the START/END markers for *name*."""
    start = f"<!--START_SECTION:{name}-->"
    end = f"<!--END_SECTION:{name}-->"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    replacement = f"{start}\n{new_body}\n{end}"
    if not pattern.search(content):
        print(f"  ! marker '{name}' not found — skipping")
        return content
    print(f"  + updated section '{name}'")
    return pattern.sub(replacement, content)


def _fetch_json(url: str) -> dict:
    req = urllib.request.Request(
        url, headers={"User-Agent": "Mozilla/5.0 (killanova-profile)"}
    )
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.load(resp)


def get_btc_price() -> str:
    """Live BTC/EUR spot price, with a fallback source so it rarely fails."""
    sources = [
        # (url, extractor)
        (
            "https://api.coinbase.com/v2/prices/BTC-EUR/spot",
            lambda d: float(d["data"]["amount"]),
        ),
        (
            "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=eur",
            lambda d: float(d["bitcoin"]["eur"]),
        ),
    ]
    for url, extract in sources:
        try:
            return f"€{extract(_fetch_json(url)):,.0f}"
        except Exception as exc:  # never let the profile build fail on a flaky API
            print(f"  ! BTC source failed ({url.split('/')[2]}): {exc}")
    return "unavailable"


def main() -> None:
    now = datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=1)
    today = now.date()
    content = README.read_text(encoding="utf-8")

    btc = get_btc_price()
    content = replace_section(
        content,
        "btc",
        f"\U0001f4b0 **BTC / EUR** &nbsp;`{btc}` &nbsp;·&nbsp; "
        f"_updated {now:%d %b %Y, %H:%M} CET_",
    )

    days = (today - FIRST_COMMIT).days
    content = replace_section(
        content,
        "coding",
        f"⏳ **{days:,} days** of building on GitHub and counting",
    )

    tip = TIPS[today.timetuple().tm_yday % len(TIPS)]
    content = replace_section(
        content,
        "tip",
        f"\U0001f4a1 **Tip of the day** — {tip}",
    )

    README.write_text(content, encoding="utf-8")
    print("Profile README updated.")


if __name__ == "__main__":
    main()
